CLASS ZBP_I_VBAK_N DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF ZI_VBAK_N.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS ZBP_I_VBAK_N IMPLEMENTATION.
ENDCLASS.