CLASS ZBP_I_SalesOrder DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF ZI_SalesOrder.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS ZBP_I_SalesOrder IMPLEMENTATION.
ENDCLASS.