CLASS ZBP_I_PurchaseOrder DEFINITION
  PUBLIC
  ABSTRACT
  FINAL
  FOR BEHAVIOR OF ZI_PurchaseOrder.

  PUBLIC SECTION.
  PROTECTED SECTION.
  PRIVATE SECTION.
ENDCLASS.

CLASS ZBP_I_PurchaseOrder IMPLEMENTATION.
ENDCLASS.